name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      OPENAI_API_KEY: "ci-dummy-key"
      OPENAI_MODEL_PARSE: "gpt-4o-mini"
      OPENAI_MODEL_REPLY: "gpt-4o-mini"
      OPENAI_TIMEOUT: "20"
      OPENAI_MAX_RETRIES: "2"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install flask flask-cors sqlalchemy openai requests pytest
      - name: Run tests
        run: pytest -q
